name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "home-assistant/actions/hassfest@master"
      - uses: "hacs/action@main"
        with:
          category: "integration"

  compat:
    name: "HA compatibility (stable)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install latest Home Assistant and deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade homeassistant xmltodict websockets voluptuous
      - name: Compile sources
        run: |
          python -m compileall -q custom_components
      - name: Import smoke test
        run: |
          python - <<'PY'
          import importlib
          import homeassistant
          mods = [
              'custom_components.novelanladv9',
              'custom_components.novelanladv9.sensor',
              'custom_components.novelanladv9.select',
              'custom_components.novelanladv9.number',
              'custom_components.novelanladv9.reading_data',
          ]
          for m in mods:
              importlib.import_module(m)
          print('Imports OK with Home Assistant', homeassistant.__version__)
          PY
